class ContentGenerator:
    """Generate sales copy and blog post content for a product.

    This module provides simple templated generation based on product details,
    audience description, and marketing angles. In a production system you could
    replace the templates with calls to a large language model.
    """

    def __init__(self):
        # Basic templates for different content types
        self.copy_templates = [
            "Introducing {product}: {angle}. Grab yours now!",
            "{angle} – that's what {product} offers to {audience}.",
            "Don't miss out on {product}. {angle}.",
        ]
        self.blog_templates = [
            "## Why {product} is a game‑changer for {audience}\n\n{intro}\n\n### Key Benefits\n{benefits}\n\n### How to get started\n{cta}",
            "# {product} Review: {angle}\n\n{intro}\n\n*Pros*: {pros}\n*Cons*: {cons}\n\n[Buy {product} now]({link})",
        ]

    def generate_sales_copy(self, product_name: str, angle: str, audience_desc: str) -> str:
        """Generate a short sales copy snippet.

        Parameters
        ----------
        product_name: str
            Name of the product.
        angle: str
            Marketing angle generated by :class:`SalesStrategist`.
        audience_desc: str
            Human‑readable description of the target audience.
        """
        template = self.copy_templates[0]
        return template.format(product=product_name, angle=angle, audience=audience_desc)

    def generate_blog_post(self, product_name: str, angle: str, audience_desc: str) -> str:
        """Generate a simple blog‑post style article.

        Returns a markdown string.
        """
        # For demonstration we fill placeholders with simple text.
        intro = f"{product_name} offers {angle.lower()}, making it perfect for {audience_desc}."
        benefits = "- High quality\n- Affordable price\n- Excellent support"
        cta = f"Visit the official site to learn more and purchase {product_name}."
        template = self.blog_templates[0]
        return template.format(
            product=product_name,
            audience=audience_desc,
            angle=angle,
            intro=intro,
            benefits=benefits,
            cta=cta,
        )

# Example usage (remove in production)
if __name__ == "__main__":
    gen = ContentGenerator()
    copy = gen.generate_sales_copy("SuperFit Tracker", "Discover how SuperFit Tracker can improve fitness for active adults", "age: 25-34; location: USA; interests: fitness, wellness")
    blog = gen.generate_blog_post("SuperFit Tracker", "Discover how SuperFit Tracker can improve fitness for active adults", "age: 25-34; location: USA; interests: fitness, wellness")
    print(copy)
    print("---")
    print(blog)
